CREATE TABLE [dbo].[Fornecedores] (
    [IdFornecedores]     INT          IDENTITY (1, 1) NOT NULL,
    [CnpjCpfForn]        VARCHAR (50) NOT NULL,
    [InscEstadualForn]   VARCHAR (50) NOT NULL,
    [OutrasInscForn]     VARCHAR (50) NOT NULL,
    [NomeForn]           VARCHAR (50) NOT NULL,
    [RazaoSocialForn]    VARCHAR (50) NOT NULL,
    [EnderecoForn]       VARCHAR (50) NOT NULL,
    [NumForn]            VARCHAR (50) NOT NULL,
    [ComplementoForn]    VARCHAR (50) NOT NULL,
    [CepForn]            VARCHAR (50) NOT NULL,
    [BairroForn]         VARCHAR (50) NOT NULL,
    [CidadeForn]         VARCHAR (50) NOT NULL,
    [UfForn]             VARCHAR (50) NOT NULL,
    [TelefoneForn]       VARCHAR (50) NOT NULL,
    [CelularForn]        VARCHAR (50) NOT NULL,
    [EmailForn]          VARCHAR (50) NOT NULL,
    [SiteForn]           VARCHAR (50) NOT NULL,
    [EnderecoCobForn]    VARCHAR (50) NOT NULL,
    [NumCobForn]         VARCHAR (50) NOT NULL,
    [ComplementoCobForn] VARCHAR (50) NOT NULL,
    [CepCobForn]         VARCHAR (50) NOT NULL,
    [BairroCobForn]      VARCHAR (50) NOT NULL,
    [CidadeCobForn]      VARCHAR (50) NOT NULL,
    [UfCobForn]          VARCHAR (50) NOT NULL,
    [ObservacaoForn]     VARCHAR (50) NOT NULL,
    [DtCadastroForn] DATETIME NOT NULL, 
    CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED ([IdFornecedores] ASC)
);

